### ISSUE TITLE
NSTextView port throws error: invalid numeric value to CoreGraphics

### ISSUE THREAD

**Issue by futurist** [fancymax/AutoCompleteTextField#1]
When port this lib into `NSTextView`, using Swift 3.0, as below:

https://github.com/futurist/cutecmd-mac/blob/4486b868cf057713704566deb304a79609632d30/cutecmd-mac/AutoCompleteTextField.swift

I have a bug reported as below:

> Nov 23 08:22:25  cutecmd-mac[6516] <Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.

This happens when the `self.getCompletionArray` returned a complete different array as before.

I've googled and told that it's due to `NSPopover`, but I'm not sure.

To reproduce it, download and run the repo, input 

**s** (will popup Safari etc.)
**Backspace** (clear the input)
**q** (this will throw above error)

**Xcode 8, macOS  10.11.6**

What's going on? help needed for the port into **NSTextView**

**Comment by fancymax** [comment]
@futurist  in macOS 10.12 Xcode8.0, I can't reproduce the problem

**Comment by futurist** [comment]
Don't know why, but will appear every time here

![untitled](https://cloud.githubusercontent.com/assets/159167/20550056/d7fd31ca-b16c-11e6-8c24-b3e116198e77.gif)

Using building completion popup (**F5**), there's no any error, but it's weak...

**Comment by futurist** [comment]
The [Swift 3.0 update](https://github.com/fancymax/AutoCompleteTextField/commit/bd2f691e39a2cbf4244f10bcc732684344bfced2) also have this problem in my mac:

![2016-11-26 8 55 34](https://cloud.githubusercontent.com/assets/159167/20637122/94c039c8-b3b7-11e6-834b-be3d7065a656.png)

**Comment by futurist** [comment]
I've moved the `popover.contentSize` calculation into a delegate method (`popoverWillShow`), and the problem gone here.

https://github.com/futurist/cutecmd-mac/commit/c8f5565fd3f7c65ce15c63e6c7ae559795e35dee#diff-cedb50a79b0833adf206a909638564aaR208

**Comment by fancymax** [comment]
@futurist thanks for your effort.  Would you mind pulling the requests?

**Comment by futurist** [comment]
If you using javascript, maybe you can check my lib:

https://github.com/cssobj/cssobj

Welcome to give a star! 😄
